databases:
  - name: sitportaldb
    databaseName: sitportaldb
    user: postgres
    plan: free

services:
  - type: web
    name: sitportal
    env: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: sitportaldb
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: sitportaldb
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: sitportaldb
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: VAPID_PUBLIC_KEY
        value: BIZRhlCjiAthaeVDsYk6XhYD-W0wByq8A65inxm8AjgA8WJQTgV1F5FDmtLP15cwPHXt3fsF5aVsFgJvu-usg7U
      - key: VAPID_PRIVATE_KEY
        value: g5y8LW8emWI87N44Rc_NFg1NbNUEKv0Ux7B22WBLfeI
      - key: CORS_ALLOWED_ORIGINS
        value: "https://sitportal.vercel.app,https://*.vercel.app,http://localhost:3000,http://127.0.0.1:3000"
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx350m -Xms128m -XX:+UseContainerSupport"
