# Spring Boot Application Config
spring.application.name=sit-cse-portal-backend
server.port=${PORT:8080}

# PostgreSQL sitportaldb Configuration (supports NeonDB, Render, Supabase, Local)
spring.datasource.url=${DATABASE_URL:${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sitportaldb}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:N@gesh7843}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate & JPA Properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Jackson JSON Formatter
spring.jackson.serialization.indent_output=true

# Spring Mail SMTP Configuration (Gmail / SIT Mail)
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:gnagesh550@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:bzjfibjkpqlesrjr}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
